#!/bin/sh
# Writes ios/Install.xcconfig, the per-install build settings.
# Usage: scripts/install-config.sh us|cn [demo-keys]
#   demo-keys: bake .env.demo's keys in (personal installs only, never the App Store build).
set -e
cd "$(dirname "$0")/.."

STORE=${1:-us}
case "$STORE" in us|cn) ;; *) echo "STORE must be us or cn, got '$STORE'"; exit 1 ;; esac

TMDB_API_KEY= OMDB_API_KEY=
if [ "$2" = demo-keys ] && [ -f .env.demo ]; then
  set -a
  . ./.env.demo
  set +a
fi

cat > ios/Install.xcconfig <<CONF
// Generated by scripts/install-config.sh; do not edit.
APP_STORE_REGION = $STORE
WTW_DEMO_TMDB_KEY = $TMDB_API_KEY
WTW_DEMO_OMDB_KEY = $OMDB_API_KEY
CONF
echo "Store: $STORE"
